name: API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  asmdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          cd api
          perl asmdoc.pl -author -version ../basic/basic.inc ../basic/modules/*.asm
          cd ..
          mkdir ../temp
          cp api/* ../temp        
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout gh-pages
          cp ../temp/* api
          git add .
          git commit -m "asmdoc"
          git push origin gh-pages
