name: build localized message bundles

on:
  push:
    paths:
    - 'locales/**'
  workflow_dispatch:

jobs:
  locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          ./scripts/locales.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "locales"
          git push origin main
