name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          cd basic
          ../scripts/rasm -pasmo basic.asm -ob ../bin/23.bin -sz -os ../bin/symbols.txt
          cd ../boot
          ../scripts/rasm -pasmo boot.asm -ob ../bin/boot.rom
          rm basic.bin
          cp ../bin/boot.rom ../bin/se.rom
          cat ../bin/basic.rom >> ../bin/se.rom
          cd ../scripts
          ./rasm firmware.asm -ob ../bin/FIRMWA~1.BIN
